name: Init Git Submodules

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  init-submodules:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Sync and update submodules
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive
          git submodule status